name: Create release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Release tag
      title:
        required: true
        description: Release title
      image:
        type: choice
        required: true
        description: Frozen image (with tag)
        options: 
        - elrondnetwork/elrond-sdk-erdpy-rust:frozen-001
        - elrondnetwork/elrond-sdk-erdpy-rust:frozen-002
        - elrondnetwork/elrond-sdk-erdpy-rust:frozen-003
        - elrondnetwork/elrond-sdk-erdpy-rust:frozen-004
        - elrondnetwork/elrond-sdk-erdpy-rust:frozen-005

permissions:
  contents: write

env:
  # https://github.com/actions/runner/issues/863 ($HOME is overridden for containers)
  ELROND_HOME: /home/elrond
  BUILD_PATH: /home/elrond
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    # See: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
    container: 
      image: ${{ github.event.inputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_REF_NAME }}
          fetch-depth: 0
          repository: ${{ env.GITHUB_REPOSITORY }}

      - name: Copy source code to build location
        run: |
          mkdir -p ${BUILD_PATH}
          cp -a /__w/${REPO_NAME}/. ${BUILD_PATH}

      - name: Build WASM files
        run: |
          # Setting $HOME is required by erdpy.
          export HOME=$ELROND_HOME
          cd ${BUILD_PATH}/${REPO_NAME}
          erdpy --verbose contract build --recursive

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-contracts
          path: |
            ${{ env.BUILD_PATH }}/**/output/*.wasm
            ${{ env.BUILD_PATH }}/**/output/*.abi.json
          if-no-files-found: error

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        with:
          path: assets

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Built using Docker image: **${{ github.event.inputs.image }}**." >> notes.txt
          echo "" >> notes.txt
          echo "## Checksums (blake2b):" >> notes.txt
          echo "" >> notes.txt

          for i in $(find ./assets -type f); do
            filename=$(basename ${i})
            checksum=($(b2sum -l 256 ${i}))
            echo " - **${filename}**: \`${checksum}\`" >> notes.txt
          done

          gh release create ${{ github.event.inputs.tag }} --target=$GITHUB_SHA --prerelease --title="${{ github.event.inputs.title }}" --generate-notes --notes-file=notes.txt
          sleep 10
          gh release upload ${{ github.event.inputs.tag }} $(find ./assets -type f)
